export default {
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    GET_SALARY: 'GET_SALARY',
    LOAD_INITIAL_DATA: 'LOAD_INITIAL_DATA',
    SAVE_SALARY: 'SAVE_SALARY',
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_MONTH:'SET_MONTH',
    SET_SALARY: 'SET_SALARY',
    SET_YEAR:'SET_YEAR',
};