export default {
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    GET_SALARY: 'GET_SALARY',
    SAVE_SALARY: 'SAVE_SALARY',
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_SALARY: 'SET_SALARY',
};
